//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbragimovI_Глазки_save
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int AgentID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int ProductCount { get; set; }

        
        public decimal Stoimost
        {
            get
            {
                decimal p = 0;
                
                p = Product.MinCostForAgent * ProductCount;
                
                return p;
            }
        }

        public string ProductIdText
        {
            get
            {
                return Product.Title;
            }
        }


        public virtual Agent Agent { get; set; }
        public virtual Product Product { get; set; }
    }
}
